"use client"
import { useEffect, useState } from "react"
import { listUsersByRole } from "@/lib/firebase/users"
import { listCoursesByTrainer } from "@/lib/firebase/courses"
import type { AppUser, Course } from "@/lib/types"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { Skeleton } from "@/components/ui/skeleton"
export default function TrainerManagementPage() { const [rows, setRows] = useState<Array<{ user: AppUser; courses: Course[] }>>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); useEffect(() => { let active = true; listUsersByRole("trainer").then(async (users) => { const result = await Promise.all(users.map(async (user) => ({ user, courses: await listCoursesByTrainer(user.uid) }))); if (active) setRows(result) }).catch((cause) => active && setError(cause instanceof Error ? cause.message : "Unable to load trainers.")).finally(() => active && setLoading(false)); return () => { active = false } }, []); return <div className="flex flex-col gap-6"><div><h1 className="text-2xl font-semibold">Trainer management</h1><p className="text-sm text-muted-foreground">Review approved trainers, expertise, and the live courses they own.</p></div>{loading ? <Skeleton className="h-48 w-full" /> : error ? <p className="text-sm text-destructive">{error}</p> : rows.length === 0 ? <p className="py-10 text-center text-sm text-muted-foreground">No trainer records yet.</p> : <div className="grid gap-4 md:grid-cols-2">{rows.map(({ user, courses }) => <Card key={user.uid}><CardHeader><div className="flex items-start justify-between gap-3"><div><CardTitle className="text-base">{user.name}</CardTitle><p className="text-sm text-muted-foreground">{user.email}</p></div><Badge variant={user.status === "approved" ? "default" : "outline"}>{user.status}</Badge></div></CardHeader><CardContent className="space-y-3"><p className="text-sm">{user.designation || "Trainer"} · {user.organization || "Organization not set"}</p><div className="flex flex-wrap gap-1.5">{(user.expertise ?? []).map((item) => <Badge key={item} variant="secondary">{item}</Badge>)}</div><p className="text-sm font-medium">{courses.length} live course{courses.length === 1 ? "" : "s"}</p></CardContent></Card>)}</div>}</div> }
